// <auto-generated />
namespace studyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CurrentWorkerId_changed_to_notRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CurrentWorkerId_changed_to_notRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201805221251552_CurrentWorkerId_changed_to_notRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
